In [1]:
import numpy as np
import pandas as pd
import datetime as dt
import matplotlib.pyplot as plt
import seaborn as sbn
%matplotlib inline

In [2]:
df = pd.read_csv("marathon_results_2017.csv")

In [3]:
df.head()

,Unnamed: 0,Bib,Name,Age,M/F,City,State,Country,Citizen,Unnamed: 9,...,25K,30K,35K,40K,Pace,Proj Time,Official Time,Overall,Gender,Division
0,0,11,"Kirui, Geoffrey",24,M,Keringet,NaN,KEN,NaN,NaN,...,1:16:59,1:33:01,1:48:19,2:02:53,0:04:57,-,2:09:37,1,1,1
1,1,17,"Rupp, Galen",30,M,Portland,OR,USA,NaN,NaN,...,1:16:59,1:33:01,1:48:19,2:03:14,0:04:58,-,2:09:58,2,2,2
2,2,23,"Osako, Suguru",25,M,Machida-City,NaN,JPN,NaN,NaN,...,1:17:00,1:33:01,1:48:31,2:03:38,0:04:59,-,2:10:28,3,3,3
3,3,21,"Biwott, Shadrack",32,M,Mammoth Lakes,CA,USA,NaN,NaN,...,1:17:00,1:33:01,1:48:58,2:04:35,0:05:03,-,2:12:08,4,4,4
4,4,9,"Chebet, Wilson",31,M,Marakwet,NaN,KEN,NaN,NaN,...,1:16:59,1:33:01,1:48:41,2:05:00,0:05:04,-,2:12:35,5,5,5

In [4]:
df.columns

Index(['Unnamed: 0', 'Bib', 'Name', 'Age', 'M/F', 'City', 'State', 'Country',
       'Citizen', 'Unnamed: 9', '5K', '10K', '15K', '20K', 'Half', '25K',
       '30K', '35K', '40K', 'Pace', 'Proj Time', 'Official Time', 'Overall',
       'Gender', 'Division'],
      dtype='object')

In [5]:
columsNames = ['Unnamed: 0', 'Bib', 'Name', 'Age', 'M/F', 'City', 'State', 'Country',
       'Citizen', '5K', '10K', '15K', '20K', 'Half', '25K',
       '30K', '35K', '40K', 'Pace', 'Proj Time', 'Official Time',
       'Gender', 'Division']
df = pd.read_csv("marathon_results_2017.csv", index_col=0, usecols=columsNames)
df.head()

,Bib,Name,Age,M/F,City,State,Country,Citizen,5K,10K,...,Half,25K,30K,35K,40K,Pace,Proj Time,Official Time,Gender,Division
0,11,"Kirui, Geoffrey",24,M,Keringet,NaN,KEN,NaN,0:15:25,0:30:28,...,1:04:35,1:16:59,1:33:01,1:48:19,2:02:53,0:04:57,-,2:09:37,1,1
1,17,"Rupp, Galen",30,M,Portland,OR,USA,NaN,0:15:24,0:30:27,...,1:04:35,1:16:59,1:33:01,1:48:19,2:03:14,0:04:58,-,2:09:58,2,2
2,23,"Osako, Suguru",25,M,Machida-City,NaN,JPN,NaN,0:15:25,0:30:29,...,1:04:36,1:17:00,1:33:01,1:48:31,2:03:38,0:04:59,-,2:10:28,3,3
3,21,"Biwott, Shadrack",32,M,Mammoth Lakes,CA,USA,NaN,0:15:25,0:30:29,...,1:04:45,1:17:00,1:33:01,1:48:58,2:04:35,0:05:03,-,2:12:08,4,4
4,9,"Chebet, Wilson",31,M,Marakwet,NaN,KEN,NaN,0:15:25,0:30:28,...,1:04:35,1:16:59,1:33:01,1:48:41,2:05:00,0:05:04,-,2:12:35,5,5

In [6]:
auxTable1 = df.groupby('Country').count().sort_values(by='Bib', ascending=False)
auxTable1 = auxTable1['Bib']

In [7]:
df.head().T

,0,1,2,3,4
Bib,11,17,23,21,9
Name,"Kirui, Geoffrey","Rupp, Galen","Osako, Suguru","Biwott, Shadrack","Chebet, Wilson"
Age,24,30,25,32,31
M/F,M,M,M,M,M
City,Keringet,Portland,Machida-City,Mammoth Lakes,Marakwet
State,NaN,OR,NaN,CA,NaN
Country,KEN,USA,JPN,USA,KEN
Citizen,NaN,NaN,NaN,NaN,NaN
5K,0:15:25,0:15:24,0:15:25,0:15:25,0:15:25
10K,0:30:28,0:30:27,0:30:29,0:30:29,0:30:28
15K,0:45:44,0:45:44,0:45:44,0:45:44,0:45:44
20K,1:01:15,1:01:15,1:01:16,1:01:19,1:01:15
Half,1:04:35,1:04:35,1:04:36,1:04:45,1:04:35
25K,1:16:59,1:16:59,1:17:00,1:17:00,1:16:59
30K,1:33:01,1:33:01,1:33:01,1:33:01,1:33:01
35K,1:48:19,1:48:19,1:48:31,1:48:58,1:48:41
40K,2:02:53,2:03:14,2:03:38,2:04:35,2:05:00
Pace,0:04:57,0:04:58,0:04:59,0:05:03,0:05:04
Proj Time,-,-,-,-,-
Official Time,2:09:37,2:09:58,2:10:28,2:12:08,2:12:35
Gender,1,2,3,4,5
Division,1,2,3,4,5

In [8]:
df.iloc[:, 8:20] = df.iloc[:, 8:20].apply(pd.to_timedelta)

In [9]:
df.dtypes

Bib                       object
Name                      object
Age                        int64
M/F                       object
City                      object
State                     object
Country                   object
Citizen                   object
5K               timedelta64[ns]
10K              timedelta64[ns]
15K              timedelta64[ns]
20K              timedelta64[ns]
Half             timedelta64[ns]
25K              timedelta64[ns]
30K              timedelta64[ns]
35K              timedelta64[ns]
40K              timedelta64[ns]
Pace             timedelta64[ns]
Proj Time        timedelta64[ns]
Official Time    timedelta64[ns]
Gender                     int64
Division                   int64
dtype: object

In [10]:
df.isnull().sum()

Bib                  0
Name                 0
Age                  0
M/F                  0
City                 0
State             3595
Country              0
Citizen          25156
5K                   0
10K                  0
15K                  0
20K                  0
Half                 0
25K                  0
30K                  0
35K                  0
40K                  0
Pace                 0
Proj Time            0
Official Time        0
Gender               0
Division             0
dtype: int64

In [11]:
df['Citizen'].value_counts()

GBR    141
CAN    131
JPN    115
CHN     78
USA     74
IRL     72
MEX     69
FRA     50
GER     46
AUS     35
ESP     27
NED     25
VEN     20
IND     19
NZL     17
POL     17
ARG     15
ITA     15
BRA     13
PHI     13
RSA     13
KOR     13
COL     12
BEL     12
DEN     10
CRC     10
SWE     10
DOM     10
SUI     10
CZE      9
      ...
NGR      2
PAK      2
TRI      2
GUY      2
LTU      2
BUL      2
EST      2
THA      2
TUN      1
CAF      1
MOZ      1
ETH      1
ZIM      1
NAM      1
BLR      1
BAN      1
ALB      1
EGY      1
ZAM      1
HON      1
JAM      1
SRI      1
LIB      1
KEN      1
LAT      1
CUB      1
BIH      1
AZE      1
SRB      1
CAM      1
Name: Citizen, Length: 85, dtype: int64

-Quienes son los mas rapido de su respectivo pais?
-En que tramos del recorrido se general los promedios de velocidades mas altas?

In [12]:
#df[df.Citizen.notnull()]

In [13]:
df['time_1'] = df['5K']
df['time_2'] = df['10K'] - df['5K']
df['time_3'] = df['15K'] - df['10K']
df['time_4'] = df['20K'] - df['15K']
df['time_5'] = df['25K'] - df['20K']
df['time_6'] = df['30K'] - df['25K']
df['time_7'] = df['35K'] - df['30K']
df['time_8'] = df['40K'] - df['35K']
df

,Bib,Name,Age,M/F,City,State,Country,Citizen,5K,10K,...,Gender,Division,time_1,time_2,time_3,time_4,time_5,time_6,time_7,time_8
0,11,"Kirui, Geoffrey",24,M,Keringet,NaN,KEN,NaN,00:15:25,00:30:28,...,1,1,00:15:25,00:15:03,00:15:16,00:15:31,00:15:44,00:16:02,00:15:18,00:14:34
1,17,"Rupp, Galen",30,M,Portland,OR,USA,NaN,00:15:24,00:30:27,...,2,2,00:15:24,00:15:03,00:15:17,00:15:31,00:15:44,00:16:02,00:15:18,00:14:55
2,23,"Osako, Suguru",25,M,Machida-City,NaN,JPN,NaN,00:15:25,00:30:29,...,3,3,00:15:25,00:15:04,00:15:15,00:15:32,00:15:44,00:16:01,00:15:30,00:15:07
3,21,"Biwott, Shadrack",32,M,Mammoth Lakes,CA,USA,NaN,00:15:25,00:30:29,...,4,4,00:15:25,00:15:04,00:15:15,00:15:35,00:15:41,00:16:01,00:15:57,00:15:37
4,9,"Chebet, Wilson",31,M,Marakwet,NaN,KEN,NaN,00:15:25,00:30:28,...,5,5,00:15:25,00:15:03,00:15:16,00:15:31,00:15:44,00:16:02,00:15:40,00:16:19
5,15,"Abdirahman, Abdi",40,M,Phoenix,AZ,USA,NaN,00:15:25,00:30:28,...,6,1,00:15:25,00:15:03,00:15:16,00:15:31,00:15:44,00:16:02,00:15:51,00:16:29
6,63,"Maiyo, Augustus K.",33,M,Colorado Springs,CO,USA,NaN,00:15:25,00:30:29,...,7,6,00:15:25,00:15:04,00:15:15,00:15:31,00:15:45,00:16:01,00:16:05,00:16:35
7,7,"Sefir, Dino",28,M,Addis Ababa,NaN,ETH,NaN,00:15:24,00:30:28,...,8,7,00:15:24,00:15:04,00:15:45,00:16:22,00:16:01,00:16:16,00:16:19,00:15:58
8,18,"Puskedra, Luke",27,M,Eugene,OR,USA,NaN,00:15:24,00:30:29,...,9,8,00:15:24,00:15:05,00:15:18,00:15:41,00:15:58,00:16:39,00:16:48,00:16:24
9,20,"Ward, Jared",28,M,Kaysville,UT,USA,NaN,00:15:25,00:30:30,...,10,9,00:15:25,00:15:05,00:15:17,00:15:41,00:15:49,00:16:32,00:16:55,00:17:10
10,22,"Quigley, Sean",32,M,Braintree,MA,USA,NaN,00:15:25,00:30:31,...,11,10,00:15:25,00:15:06,00:15:32,00:16:08,00:16:09,00:16:38,00:16:57,00:16:15
11,6,"Tsegay, Yemane",32,M,Addis Ababa,NaN,ETH,NaN,00:15:24,00:30:27,...,12,11,00:15:24,00:15:03,00:15:17,00:15:31,00:16:15,00:17:03,00:17:27,00:16:57
12,14,"Keflezighi, Meb",41,M,San Diego,CA,USA,NaN,00:15:24,00:30:27,...,13,2,00:15:24,00:15:03,00:15:18,00:15:43,00:16:15,00:17:00,00:17:14,00:17:12
13,16,"Nyasango, Cutbert",34,M,Harara,NaN,ZIM,NaN,00:15:26,00:31:13,...,14,12,00:15:26,00:15:47,00:15:57,00:16:18,00:16:26,00:16:45,00:17:16,00:16:25
14,10,"Korir, Wesley",34,M,Kitale,NaN,KEN,NaN,00:15:24,00:30:28,...,15,13,00:15:24,00:15:04,00:15:16,00:15:31,00:15:53,00:17:09,00:17:33,00:18:08
15,35,"Puzey, Thomas R.",32,M,Flagstaff,AZ,USA,NaN,00:16:23,00:32:47,...,16,14,00:16:23,00:16:24,00:16:25,00:16:37,00:16:28,00:16:34,00:16:26,00:15:57
16,76,"Kisri, Rachid",41,M,Briarcliff Manor,NY,USA,MAR,00:15:24,00:30:29,...,17,3,00:15:24,00:15:05,00:15:29,00:16:07,00:16:15,00:17:13,00:17:37,00:17:26
17,3,"Mutai, Emmanuel",32,M,Lessos,NaN,KEN,NaN,00:15:24,00:30:27,...,18,15,00:15:24,00:15:03,00:15:16,00:15:32,00:15:44,00:16:25,00:18:08,00:19:12
18,30,"Ndhlovu, Pardon",29,M,Vilas,NC,USA,ZIM,00:15:40,00:31:21,...,19,16,00:15:40,00:15:41,00:15:58,00:16:08,00:16:26,00:16:45,00:17:16,00:17:42
19,31,"Harvey, Brian",29,M,Boston,MA,USA,NaN,00:16:10,00:32:34,...,20,17,00:16:10,00:16:24,00:16:20,00:16:23,00:16:28,00:16:49,00:17:14,00:17:03
20,F3,"Kiplagat, Edna",37,F,Uasin Gishu,NaN,KEN,NaN,00:17:46,00:34:58,...,1,1,00:17:46,00:17:12,00:16:57,00:16:55,00:17:01,00:16:49,00:16:01,00:16:02
21,81,"Chipsiya, Christopher K.",42,M,Zacatecas,NaN,MEX,KEN,00:15:25,00:30:31,...,21,4,00:15:25,00:15:06,00:15:15,00:16:07,00:16:47,00:18:03,00:19:09,00:18:23
22,101,"Mindel, Scott",30,M,Arlington,MA,USA,NaN,00:16:38,00:33:26,...,22,18,00:16:38,00:16:48,00:16:37,00:16:34,00:16:42,00:16:50,00:17:11,00:17:14
23,F11,"Chelimo, Rose",27,F,Manama,NaN,BRN,NaN,00:17:45,00:34:58,...,2,2,00:17:45,00:17:13,00:16:57,00:16:55,00:17:00,00:16:50,00:16:35,00:16:27
24,F23,"Hasay, Jordan",25,F,Beaverton,OR,USA,NaN,00:17:45,00:34:58,...,3,3,00:17:45,00:17:13,00:16:57,00:16:55,00:17:01,00:16:50,00:16:45,00:16:28
25,182,"Place, Ryan J",31,M,Cambridge,MA,USA,NaN,00:16:28,00:33:18,...,23,19,00:16:28,00:16:50,00:16:37,00:16:36,00:16:42,00:16:59,00:17:28,00:17:34
26,33,"Humphrey, Luke",36,M,Beverly Hills,MI,USA,NaN,00:16:31,00:32:58,...,24,20,00:16:31,00:16:27,00:16:28,00:16:35,00:16:31,00:17:13,00:17:56,00:17:33
27,28,"Ashe, Eric",28,M,Boston,MA,USA,NaN,00:16:37,00:33:27,...,25,21,00:16:37,00:16:50,00:16:47,00:16:38,00:16:37,00:16:45,00:17:10,00:18:03
28,53,"Thompson, Christian C.",28,M,Chattanooga,TN,USA,NaN,00:16:20,00:32:48,...,26,22,00:16:20,00:16:28,00:16:46,00:16:52,00:16:57,00:17:30,00:17:52,00:17:22
29,43,"Maravilla, Jorge",39,M,Mill Valley,CA,USA,NaN,00:16:37,00:33:29,...,27,23,00:16:37,00:16:52,00:16:51,00:16:59,00:17:16,00:17:30,00:17:40,00:16:36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26380,25779,"Nijensohn, Lynda A.",42,F,Wellesley,MA,USA,NaN,00:34:14,01:10:13,...,11966,1853,00:34:14,00:35:59,00:35:39,00:36:37,00:42:14,00:53:38,00:56:53,00:52:16
26381,24894,"Staveley, Patricia",60,F,Calgary,AB,CAN,NaN,00:35:07,01:14:23,...,11967,343,00:35:07,00:39:16,00:40:04,00:42:38,00:42:41,00:49:43,00:57:42,00:44:08
26382,23144,"Fong, Sut Sam",48,F,Hong Kong,NaN,HKG,NaN,00:33:30,01:09:43,...,11968,1862,00:33:30,00:36:13,00:39:25,00:42:09,01:05:56,00:48:45,00:46:29,00:42:37
26383,25182,"Trang, Danh",30,M,San Francisco,CA,USA,NaN,00:35:53,01:12:42,...,14417,4766,00:35:53,00:36:49,00:38:30,00:39:59,00:42:21,01:01:16,00:51:33,00:49:39
26384,26163,"Prario, Austin D.",19,M,Mapleville,RI,USA,NaN,00:33:35,01:11:58,...,14418,4767,00:33:35,00:38:23,00:39:38,00:41:40,00:43:36,00:47:53,00:55:55,00:54:04
26385,26889,"Welch, Jennifer E.",37,F,Boston,MA,USA,NaN,00:33:59,01:11:09,...,11969,5846,00:33:59,00:37:10,00:39:48,00:43:17,00:48:25,00:52:47,00:52:25,00:47:14
26386,26873,"Wolff, Eli A.",39,M,Newton,MA,USA,NaN,00:34:01,01:11:12,...,14419,4768,00:34:01,00:37:11,00:39:48,00:43:17,00:48:24,00:52:47,00:52:26,00:47:14
26387,23458,"Pulido, Jose I Sr.",66,M,Bogota,NaN,COL,NaN,00:29:35,01:01:18,...,14420,424,00:29:35,00:31:43,00:34:05,00:38:32,00:57:26,00:53:49,00:56:05,00:51:30
26388,25179,"Solberg, Bryon",55,M,San Diego,CA,USA,NaN,00:40:07,01:24:52,...,14421,1535,00:40:07,00:44:45,00:44:11,00:43:16,00:44:59,00:44:32,00:48:14,00:46:49
26389,25265,"Picard, Hector",50,M,Fort Lauderdale,FL,USA,NaN,00:36:17,01:17:02,...,14422,1945,00:36:17,00:40:45,00:44:19,00:43:51,00:46:40,00:47:30,00:51:08,00:51:13
26390,28988,"Taylor, Robert",56,M,Ft Lauderdale,FL,USA,NaN,00:36:18,01:17:33,...,14423,1536,00:36:18,00:41:15,00:44:03,00:44:11,00:46:18,00:47:40,00:50:41,00:51:49
26391,6893,"Ueda, Akifumi",58,M,Himeji-Shi,NaN,JPN,NaN,00:28:48,01:00:28,...,14424,1537,00:28:48,00:31:40,00:36:13,00:43:01,00:52:36,00:52:21,00:55:43,00:56:37
26392,10603,"Ferry, J. Alain",45,M,Boston,MA,USA,NaN,00:39:15,01:24:29,...,14425,2551,00:39:15,00:45:14,00:48:36,00:47:06,00:48:31,00:49:00,00:45:48,00:43:51
26393,27054,"Weisberg, Scott R.",47,M,Birmingham,AL,USA,NaN,00:46:41,01:28:49,...,14426,2552,00:46:41,00:42:08,00:39:19,00:39:41,00:40:28,00:49:58,00:56:37,00:51:51
26394,6170,"Morris, Sheldon",44,M,Springhill,NS,CAN,NaN,00:38:29,01:24:33,...,14427,1988,00:38:29,00:46:04,00:46:13,00:47:03,00:50:58,00:49:09,00:47:43,00:49:36
26395,4631,"Choon Hon, Lim",33,M,Singapore,NaN,SIN,NaN,00:38:23,01:21:54,...,14428,4769,00:38:23,00:43:31,00:41:40,00:45:28,00:54:57,00:50:11,00:48:32,00:49:13
26396,25262,"Caesar, Candice L.",44,F,Fresno,TX,USA,NaN,00:35:47,01:17:02,...,11970,1854,00:35:47,00:41:15,00:48:56,00:46:35,00:50:59,00:54:19,00:53:27,00:47:03
26397,15536,"Coffman, Steven D.",69,M,East Sandwich,MA,USA,NaN,00:32:14,01:10:24,...,14429,425,00:32:14,00:38:10,00:49:20,00:51:30,00:55:34,00:57:04,00:53:31,00:46:39
26398,14851,"Scholtz, Theo E",70,M,Wylie,TX,USA,NaN,00:25:32,00:54:42,...,14430,138,00:25:32,00:29:10,00:36:05,00:40:45,01:02:23,01:00:14,01:11:10,00:55:37
26399,25263,"Luckett, Kelly",49,F,Savannah,GA,USA,NaN,00:42:31,01:27:45,...,11971,1863,00:42:31,00:45:14,00:50:18,00:47:49,00:49:58,00:51:45,00:50:57,00:47:24
26400,2605,"Mederos, Jonathan",32,M,South Miami,FL,USA,NaN,00:20:55,00:42:11,...,14431,4770,00:20:55,00:21:16,00:23:20,00:27:04,00:30:59,00:43:37,02:58:40,00:41:31
26401,15547,"Elliott, Gregory J.",68,M,Chicago,IL,USA,NaN,00:32:16,01:10:13,...,14432,426,00:32:16,00:37:57,00:45:54,00:54:03,00:53:58,00:57:25,01:01:02,00:48:53
26402,3070,"Galbraith, Jordan M",30,M,Cardston,AB,CAN,NaN,00:23:10,00:47:20,...,14433,4771,00:23:10,00:24:10,00:28:29,00:41:49,01:04:20,01:27:43,00:58:49,00:58:58
26403,31283,"Leroy, Stefan M.",25,M,Jupiter,FL,USA,NaN,00:39:58,01:25:53,...,14434,4772,00:39:58,00:45:55,00:44:28,00:50:46,00:51:59,00:56:34,00:53:11,00:51:37
26404,25141,"Quinn, Adam H.",19,M,Belmont,MI,USA,NaN,00:35:14,01:10:33,...,14435,4773,00:35:14,00:35:19,00:37:17,00:46:08,01:27:13,00:41:48,00:50:16,01:09:36
26405,25166,"Steinbach, Paula Eyvonne",61,F,Ontario,CA,USA,NaN,00:46:44,01:35:41,...,11972,344,00:46:44,00:48:57,00:47:54,00:49:09,00:59:22,00:51:02,00:52:10,00:51:39
26406,25178,"Avelino, Andrew R.",25,M,Fayetteville,NC,USA,NaN,00:32:03,01:05:33,...,14436,4774,00:32:03,00:33:30,00:46:44,00:57:24,01:00:38,00:59:42,01:03:47,01:00:33
26407,27086,"Hantel, Johanna",57,F,Malvern,PA,USA,NaN,00:53:11,01:43:36,...,11973,698,00:53:11,00:50:25,00:49:00,-1 days +21:27:24,04:15:21,00:51:16,00:53:56,00:54:05
26408,25268,"Reilly, Bill",64,M,New York,NY,USA,NaN,00:40:34,01:27:19,...,14437,1043,00:40:34,00:46:45,00:49:58,00:54:23,00:54:30,01:00:59,00:58:58,00:50:01
26409,25266,"Rigsby, Scott",48,M,Alpharetta,GA,USA,NaN,00:39:36,01:17:12,...,14438,2553,00:39:36,00:37:36,00:42:58,00:58:45,01:28:19,01:09:59,01:01:54,01:02:16

In [14]:
def toSeconds(cell):
    return cell.total_seconds()
def rowsToSecods(dataFrame, arr):
    for raw in arr:
        dataFrame[raw] = dataFrame.apply (lambda row: toSeconds(row[raw]),axis=1)
    return dataFrame
df.columns

Index(['Bib', 'Name', 'Age', 'M/F', 'City', 'State', 'Country', 'Citizen',
       '5K', '10K', '15K', '20K', 'Half', '25K', '30K', '35K', '40K', 'Pace',
       'Proj Time', 'Official Time', 'Gender', 'Division', 'time_1', 'time_2',
       'time_3', 'time_4', 'time_5', 'time_6', 'time_7', 'time_8'],
      dtype='object')

In [15]:
timeColumns = ['time_1', 'time_2',
       'time_3', 'time_4', 'time_5', 'time_6', 'time_7', 'time_8']
df = rowsToSecods(df, timeColumns)
df

,Bib,Name,Age,M/F,City,State,Country,Citizen,5K,10K,...,Gender,Division,time_1,time_2,time_3,time_4,time_5,time_6,time_7,time_8
0,11,"Kirui, Geoffrey",24,M,Keringet,NaN,KEN,NaN,00:15:25,00:30:28,...,1,1,925.0,903.0,916.0,931.0,944.0,962.0,918.0,874.0
1,17,"Rupp, Galen",30,M,Portland,OR,USA,NaN,00:15:24,00:30:27,...,2,2,924.0,903.0,917.0,931.0,944.0,962.0,918.0,895.0
2,23,"Osako, Suguru",25,M,Machida-City,NaN,JPN,NaN,00:15:25,00:30:29,...,3,3,925.0,904.0,915.0,932.0,944.0,961.0,930.0,907.0
3,21,"Biwott, Shadrack",32,M,Mammoth Lakes,CA,USA,NaN,00:15:25,00:30:29,...,4,4,925.0,904.0,915.0,935.0,941.0,961.0,957.0,937.0
4,9,"Chebet, Wilson",31,M,Marakwet,NaN,KEN,NaN,00:15:25,00:30:28,...,5,5,925.0,903.0,916.0,931.0,944.0,962.0,940.0,979.0
5,15,"Abdirahman, Abdi",40,M,Phoenix,AZ,USA,NaN,00:15:25,00:30:28,...,6,1,925.0,903.0,916.0,931.0,944.0,962.0,951.0,989.0
6,63,"Maiyo, Augustus K.",33,M,Colorado Springs,CO,USA,NaN,00:15:25,00:30:29,...,7,6,925.0,904.0,915.0,931.0,945.0,961.0,965.0,995.0
7,7,"Sefir, Dino",28,M,Addis Ababa,NaN,ETH,NaN,00:15:24,00:30:28,...,8,7,924.0,904.0,945.0,982.0,961.0,976.0,979.0,958.0
8,18,"Puskedra, Luke",27,M,Eugene,OR,USA,NaN,00:15:24,00:30:29,...,9,8,924.0,905.0,918.0,941.0,958.0,999.0,1008.0,984.0
9,20,"Ward, Jared",28,M,Kaysville,UT,USA,NaN,00:15:25,00:30:30,...,10,9,925.0,905.0,917.0,941.0,949.0,992.0,1015.0,1030.0
10,22,"Quigley, Sean",32,M,Braintree,MA,USA,NaN,00:15:25,00:30:31,...,11,10,925.0,906.0,932.0,968.0,969.0,998.0,1017.0,975.0
11,6,"Tsegay, Yemane",32,M,Addis Ababa,NaN,ETH,NaN,00:15:24,00:30:27,...,12,11,924.0,903.0,917.0,931.0,975.0,1023.0,1047.0,1017.0
12,14,"Keflezighi, Meb",41,M,San Diego,CA,USA,NaN,00:15:24,00:30:27,...,13,2,924.0,903.0,918.0,943.0,975.0,1020.0,1034.0,1032.0
13,16,"Nyasango, Cutbert",34,M,Harara,NaN,ZIM,NaN,00:15:26,00:31:13,...,14,12,926.0,947.0,957.0,978.0,986.0,1005.0,1036.0,985.0
14,10,"Korir, Wesley",34,M,Kitale,NaN,KEN,NaN,00:15:24,00:30:28,...,15,13,924.0,904.0,916.0,931.0,953.0,1029.0,1053.0,1088.0
15,35,"Puzey, Thomas R.",32,M,Flagstaff,AZ,USA,NaN,00:16:23,00:32:47,...,16,14,983.0,984.0,985.0,997.0,988.0,994.0,986.0,957.0
16,76,"Kisri, Rachid",41,M,Briarcliff Manor,NY,USA,MAR,00:15:24,00:30:29,...,17,3,924.0,905.0,929.0,967.0,975.0,1033.0,1057.0,1046.0
17,3,"Mutai, Emmanuel",32,M,Lessos,NaN,KEN,NaN,00:15:24,00:30:27,...,18,15,924.0,903.0,916.0,932.0,944.0,985.0,1088.0,1152.0
18,30,"Ndhlovu, Pardon",29,M,Vilas,NC,USA,ZIM,00:15:40,00:31:21,...,19,16,940.0,941.0,958.0,968.0,986.0,1005.0,1036.0,1062.0
19,31,"Harvey, Brian",29,M,Boston,MA,USA,NaN,00:16:10,00:32:34,...,20,17,970.0,984.0,980.0,983.0,988.0,1009.0,1034.0,1023.0
20,F3,"Kiplagat, Edna",37,F,Uasin Gishu,NaN,KEN,NaN,00:17:46,00:34:58,...,1,1,1066.0,1032.0,1017.0,1015.0,1021.0,1009.0,961.0,962.0
21,81,"Chipsiya, Christopher K.",42,M,Zacatecas,NaN,MEX,KEN,00:15:25,00:30:31,...,21,4,925.0,906.0,915.0,967.0,1007.0,1083.0,1149.0,1103.0
22,101,"Mindel, Scott",30,M,Arlington,MA,USA,NaN,00:16:38,00:33:26,...,22,18,998.0,1008.0,997.0,994.0,1002.0,1010.0,1031.0,1034.0
23,F11,"Chelimo, Rose",27,F,Manama,NaN,BRN,NaN,00:17:45,00:34:58,...,2,2,1065.0,1033.0,1017.0,1015.0,1020.0,1010.0,995.0,987.0
24,F23,"Hasay, Jordan",25,F,Beaverton,OR,USA,NaN,00:17:45,00:34:58,...,3,3,1065.0,1033.0,1017.0,1015.0,1021.0,1010.0,1005.0,988.0
25,182,"Place, Ryan J",31,M,Cambridge,MA,USA,NaN,00:16:28,00:33:18,...,23,19,988.0,1010.0,997.0,996.0,1002.0,1019.0,1048.0,1054.0
26,33,"Humphrey, Luke",36,M,Beverly Hills,MI,USA,NaN,00:16:31,00:32:58,...,24,20,991.0,987.0,988.0,995.0,991.0,1033.0,1076.0,1053.0
27,28,"Ashe, Eric",28,M,Boston,MA,USA,NaN,00:16:37,00:33:27,...,25,21,997.0,1010.0,1007.0,998.0,997.0,1005.0,1030.0,1083.0
28,53,"Thompson, Christian C.",28,M,Chattanooga,TN,USA,NaN,00:16:20,00:32:48,...,26,22,980.0,988.0,1006.0,1012.0,1017.0,1050.0,1072.0,1042.0
29,43,"Maravilla, Jorge",39,M,Mill Valley,CA,USA,NaN,00:16:37,00:33:29,...,27,23,997.0,1012.0,1011.0,1019.0,1036.0,1050.0,1060.0,996.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26380,25779,"Nijensohn, Lynda A.",42,F,Wellesley,MA,USA,NaN,00:34:14,01:10:13,...,11966,1853,2054.0,2159.0,2139.0,2197.0,2534.0,3218.0,3413.0,3136.0
26381,24894,"Staveley, Patricia",60,F,Calgary,AB,CAN,NaN,00:35:07,01:14:23,...,11967,343,2107.0,2356.0,2404.0,2558.0,2561.0,2983.0,3462.0,2648.0
26382,23144,"Fong, Sut Sam",48,F,Hong Kong,NaN,HKG,NaN,00:33:30,01:09:43,...,11968,1862,2010.0,2173.0,2365.0,2529.0,3956.0,2925.0,2789.0,2557.0
26383,25182,"Trang, Danh",30,M,San Francisco,CA,USA,NaN,00:35:53,01:12:42,...,14417,4766,2153.0,2209.0,2310.0,2399.0,2541.0,3676.0,3093.0,2979.0
26384,26163,"Prario, Austin D.",19,M,Mapleville,RI,USA,NaN,00:33:35,01:11:58,...,14418,4767,2015.0,2303.0,2378.0,2500.0,2616.0,2873.0,3355.0,3244.0
26385,26889,"Welch, Jennifer E.",37,F,Boston,MA,USA,NaN,00:33:59,01:11:09,...,11969,5846,2039.0,2230.0,2388.0,2597.0,2905.0,3167.0,3145.0,2834.0
26386,26873,"Wolff, Eli A.",39,M,Newton,MA,USA,NaN,00:34:01,01:11:12,...,14419,4768,2041.0,2231.0,2388.0,2597.0,2904.0,3167.0,3146.0,2834.0
26387,23458,"Pulido, Jose I Sr.",66,M,Bogota,NaN,COL,NaN,00:29:35,01:01:18,...,14420,424,1775.0,1903.0,2045.0,2312.0,3446.0,3229.0,3365.0,3090.0
26388,25179,"Solberg, Bryon",55,M,San Diego,CA,USA,NaN,00:40:07,01:24:52,...,14421,1535,2407.0,2685.0,2651.0,2596.0,2699.0,2672.0,2894.0,2809.0
26389,25265,"Picard, Hector",50,M,Fort Lauderdale,FL,USA,NaN,00:36:17,01:17:02,...,14422,1945,2177.0,2445.0,2659.0,2631.0,2800.0,2850.0,3068.0,3073.0
26390,28988,"Taylor, Robert",56,M,Ft Lauderdale,FL,USA,NaN,00:36:18,01:17:33,...,14423,1536,2178.0,2475.0,2643.0,2651.0,2778.0,2860.0,3041.0,3109.0
26391,6893,"Ueda, Akifumi",58,M,Himeji-Shi,NaN,JPN,NaN,00:28:48,01:00:28,...,14424,1537,1728.0,1900.0,2173.0,2581.0,3156.0,3141.0,3343.0,3397.0
26392,10603,"Ferry, J. Alain",45,M,Boston,MA,USA,NaN,00:39:15,01:24:29,...,14425,2551,2355.0,2714.0,2916.0,2826.0,2911.0,2940.0,2748.0,2631.0
26393,27054,"Weisberg, Scott R.",47,M,Birmingham,AL,USA,NaN,00:46:41,01:28:49,...,14426,2552,2801.0,2528.0,2359.0,2381.0,2428.0,2998.0,3397.0,3111.0
26394,6170,"Morris, Sheldon",44,M,Springhill,NS,CAN,NaN,00:38:29,01:24:33,...,14427,1988,2309.0,2764.0,2773.0,2823.0,3058.0,2949.0,2863.0,2976.0
26395,4631,"Choon Hon, Lim",33,M,Singapore,NaN,SIN,NaN,00:38:23,01:21:54,...,14428,4769,2303.0,2611.0,2500.0,2728.0,3297.0,3011.0,2912.0,2953.0
26396,25262,"Caesar, Candice L.",44,F,Fresno,TX,USA,NaN,00:35:47,01:17:02,...,11970,1854,2147.0,2475.0,2936.0,2795.0,3059.0,3259.0,3207.0,2823.0
26397,15536,"Coffman, Steven D.",69,M,East Sandwich,MA,USA,NaN,00:32:14,01:10:24,...,14429,425,1934.0,2290.0,2960.0,3090.0,3334.0,3424.0,3211.0,2799.0
26398,14851,"Scholtz, Theo E",70,M,Wylie,TX,USA,NaN,00:25:32,00:54:42,...,14430,138,1532.0,1750.0,2165.0,2445.0,3743.0,3614.0,4270.0,3337.0
26399,25263,"Luckett, Kelly",49,F,Savannah,GA,USA,NaN,00:42:31,01:27:45,...,11971,1863,2551.0,2714.0,3018.0,2869.0,2998.0,3105.0,3057.0,2844.0
26400,2605,"Mederos, Jonathan",32,M,South Miami,FL,USA,NaN,00:20:55,00:42:11,...,14431,4770,1255.0,1276.0,1400.0,1624.0,1859.0,2617.0,10720.0,2491.0
26401,15547,"Elliott, Gregory J.",68,M,Chicago,IL,USA,NaN,00:32:16,01:10:13,...,14432,426,1936.0,2277.0,2754.0,3243.0,3238.0,3445.0,3662.0,2933.0
26402,3070,"Galbraith, Jordan M",30,M,Cardston,AB,CAN,NaN,00:23:10,00:47:20,...,14433,4771,1390.0,1450.0,1709.0,2509.0,3860.0,5263.0,3529.0,3538.0
26403,31283,"Leroy, Stefan M.",25,M,Jupiter,FL,USA,NaN,00:39:58,01:25:53,...,14434,4772,2398.0,2755.0,2668.0,3046.0,3119.0,3394.0,3191.0,3097.0
26404,25141,"Quinn, Adam H.",19,M,Belmont,MI,USA,NaN,00:35:14,01:10:33,...,14435,4773,2114.0,2119.0,2237.0,2768.0,5233.0,2508.0,3016.0,4176.0
26405,25166,"Steinbach, Paula Eyvonne",61,F,Ontario,CA,USA,NaN,00:46:44,01:35:41,...,11972,344,2804.0,2937.0,2874.0,2949.0,3562.0,3062.0,3130.0,3099.0
26406,25178,"Avelino, Andrew R.",25,M,Fayetteville,NC,USA,NaN,00:32:03,01:05:33,...,14436,4774,1923.0,2010.0,2804.0,3444.0,3638.0,3582.0,3827.0,3633.0
26407,27086,"Hantel, Johanna",57,F,Malvern,PA,USA,NaN,00:53:11,01:43:36,...,11973,698,3191.0,3025.0,2940.0,-9156.0,15321.0,3076.0,3236.0,3245.0
26408,25268,"Reilly, Bill",64,M,New York,NY,USA,NaN,00:40:34,01:27:19,...,14437,1043,2434.0,2805.0,2998.0,3263.0,3270.0,3659.0,3538.0,3001.0
26409,25266,"Rigsby, Scott",48,M,Alpharetta,GA,USA,NaN,00:39:36,01:17:12,...,14438,2553,2376.0,2256.0,2578.0,3525.0,5299.0,4199.0,3714.0,3736.0

In [16]:
df.shape

(26410, 30)

In [17]:
df = df[(df['time_1'] > 0) & 
   (df['time_2'] > 0) &
   (df['time_3'] > 0) &
   (df['time_4'] > 0) &
   (df['time_5'] > 0) &
   (df['time_6'] > 0) &
   (df['time_7'] > 0) &
   (df['time_8'] > 0)]
df.shape

(26262, 30)

In [18]:
df = df[(df['time_1'] < df['time_1'].median()) & 
   (df['time_2'] < df['time_2'].median()) &
   (df['time_3'] < df['time_3'].median()) &
   (df['time_4'] < df['time_4'].median()) &
   (df['time_5'] < df['time_5'].median()) &
   (df['time_6'] < df['time_6'].median()) &
   (df['time_7'] < df['time_7'].median()) &
   (df['time_8'] < df['time_8'].median())]
df.shape

(8397, 30)

In [19]:
df

,Bib,Name,Age,M/F,City,State,Country,Citizen,5K,10K,...,Gender,Division,time_1,time_2,time_3,time_4,time_5,time_6,time_7,time_8
0,11,"Kirui, Geoffrey",24,M,Keringet,NaN,KEN,NaN,00:15:25,00:30:28,...,1,1,925.0,903.0,916.0,931.0,944.0,962.0,918.0,874.0
1,17,"Rupp, Galen",30,M,Portland,OR,USA,NaN,00:15:24,00:30:27,...,2,2,924.0,903.0,917.0,931.0,944.0,962.0,918.0,895.0
2,23,"Osako, Suguru",25,M,Machida-City,NaN,JPN,NaN,00:15:25,00:30:29,...,3,3,925.0,904.0,915.0,932.0,944.0,961.0,930.0,907.0
3,21,"Biwott, Shadrack",32,M,Mammoth Lakes,CA,USA,NaN,00:15:25,00:30:29,...,4,4,925.0,904.0,915.0,935.0,941.0,961.0,957.0,937.0
4,9,"Chebet, Wilson",31,M,Marakwet,NaN,KEN,NaN,00:15:25,00:30:28,...,5,5,925.0,903.0,916.0,931.0,944.0,962.0,940.0,979.0
5,15,"Abdirahman, Abdi",40,M,Phoenix,AZ,USA,NaN,00:15:25,00:30:28,...,6,1,925.0,903.0,916.0,931.0,944.0,962.0,951.0,989.0
6,63,"Maiyo, Augustus K.",33,M,Colorado Springs,CO,USA,NaN,00:15:25,00:30:29,...,7,6,925.0,904.0,915.0,931.0,945.0,961.0,965.0,995.0
7,7,"Sefir, Dino",28,M,Addis Ababa,NaN,ETH,NaN,00:15:24,00:30:28,...,8,7,924.0,904.0,945.0,982.0,961.0,976.0,979.0,958.0
8,18,"Puskedra, Luke",27,M,Eugene,OR,USA,NaN,00:15:24,00:30:29,...,9,8,924.0,905.0,918.0,941.0,958.0,999.0,1008.0,984.0
9,20,"Ward, Jared",28,M,Kaysville,UT,USA,NaN,00:15:25,00:30:30,...,10,9,925.0,905.0,917.0,941.0,949.0,992.0,1015.0,1030.0
10,22,"Quigley, Sean",32,M,Braintree,MA,USA,NaN,00:15:25,00:30:31,...,11,10,925.0,906.0,932.0,968.0,969.0,998.0,1017.0,975.0
11,6,"Tsegay, Yemane",32,M,Addis Ababa,NaN,ETH,NaN,00:15:24,00:30:27,...,12,11,924.0,903.0,917.0,931.0,975.0,1023.0,1047.0,1017.0
12,14,"Keflezighi, Meb",41,M,San Diego,CA,USA,NaN,00:15:24,00:30:27,...,13,2,924.0,903.0,918.0,943.0,975.0,1020.0,1034.0,1032.0
13,16,"Nyasango, Cutbert",34,M,Harara,NaN,ZIM,NaN,00:15:26,00:31:13,...,14,12,926.0,947.0,957.0,978.0,986.0,1005.0,1036.0,985.0
14,10,"Korir, Wesley",34,M,Kitale,NaN,KEN,NaN,00:15:24,00:30:28,...,15,13,924.0,904.0,916.0,931.0,953.0,1029.0,1053.0,1088.0
15,35,"Puzey, Thomas R.",32,M,Flagstaff,AZ,USA,NaN,00:16:23,00:32:47,...,16,14,983.0,984.0,985.0,997.0,988.0,994.0,986.0,957.0
16,76,"Kisri, Rachid",41,M,Briarcliff Manor,NY,USA,MAR,00:15:24,00:30:29,...,17,3,924.0,905.0,929.0,967.0,975.0,1033.0,1057.0,1046.0
17,3,"Mutai, Emmanuel",32,M,Lessos,NaN,KEN,NaN,00:15:24,00:30:27,...,18,15,924.0,903.0,916.0,932.0,944.0,985.0,1088.0,1152.0
18,30,"Ndhlovu, Pardon",29,M,Vilas,NC,USA,ZIM,00:15:40,00:31:21,...,19,16,940.0,941.0,958.0,968.0,986.0,1005.0,1036.0,1062.0
19,31,"Harvey, Brian",29,M,Boston,MA,USA,NaN,00:16:10,00:32:34,...,20,17,970.0,984.0,980.0,983.0,988.0,1009.0,1034.0,1023.0
20,F3,"Kiplagat, Edna",37,F,Uasin Gishu,NaN,KEN,NaN,00:17:46,00:34:58,...,1,1,1066.0,1032.0,1017.0,1015.0,1021.0,1009.0,961.0,962.0
21,81,"Chipsiya, Christopher K.",42,M,Zacatecas,NaN,MEX,KEN,00:15:25,00:30:31,...,21,4,925.0,906.0,915.0,967.0,1007.0,1083.0,1149.0,1103.0
22,101,"Mindel, Scott",30,M,Arlington,MA,USA,NaN,00:16:38,00:33:26,...,22,18,998.0,1008.0,997.0,994.0,1002.0,1010.0,1031.0,1034.0
23,F11,"Chelimo, Rose",27,F,Manama,NaN,BRN,NaN,00:17:45,00:34:58,...,2,2,1065.0,1033.0,1017.0,1015.0,1020.0,1010.0,995.0,987.0
24,F23,"Hasay, Jordan",25,F,Beaverton,OR,USA,NaN,00:17:45,00:34:58,...,3,3,1065.0,1033.0,1017.0,1015.0,1021.0,1010.0,1005.0,988.0
25,182,"Place, Ryan J",31,M,Cambridge,MA,USA,NaN,00:16:28,00:33:18,...,23,19,988.0,1010.0,997.0,996.0,1002.0,1019.0,1048.0,1054.0
26,33,"Humphrey, Luke",36,M,Beverly Hills,MI,USA,NaN,00:16:31,00:32:58,...,24,20,991.0,987.0,988.0,995.0,991.0,1033.0,1076.0,1053.0
27,28,"Ashe, Eric",28,M,Boston,MA,USA,NaN,00:16:37,00:33:27,...,25,21,997.0,1010.0,1007.0,998.0,997.0,1005.0,1030.0,1083.0
28,53,"Thompson, Christian C.",28,M,Chattanooga,TN,USA,NaN,00:16:20,00:32:48,...,26,22,980.0,988.0,1006.0,1012.0,1017.0,1050.0,1072.0,1042.0
29,43,"Maravilla, Jorge",39,M,Mill Valley,CA,USA,NaN,00:16:37,00:33:29,...,27,23,997.0,1012.0,1011.0,1019.0,1036.0,1050.0,1060.0,996.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11102,14060,"Evans, Rob",54,M,Toronto,ON,CAN,NaN,00:25:02,00:49:28,...,7712,898,1502.0,1466.0,1475.0,1518.0,1549.0,1651.0,1721.0,1787.0
11138,11618,"Martinez, Myriam",41,F,Astoria,NY,USA,NaN,00:24:41,00:49:10,...,3415,538,1481.0,1469.0,1510.0,1572.0,1597.0,1673.0,1752.0,1712.0
11161,18279,"Bryan, Beth C",54,F,Tampa,FL,USA,NaN,00:24:40,00:48:49,...,3426,124,1480.0,1449.0,1438.0,1520.0,1601.0,1705.0,1776.0,1736.0
11163,17211,"Goldberg, Lew",66,M,Fairfax,VA,USA,NaN,00:24:59,00:49:51,...,7738,30,1499.0,1492.0,1513.0,1567.0,1593.0,1684.0,1727.0,1688.0
11182,15398,"Knak, Iana",35,F,Bassano Del Grappa,NaN,ITA,BRA,00:24:46,00:49:47,...,3436,2406,1486.0,1501.0,1523.0,1566.0,1586.0,1662.0,1737.0,1673.0
11186,17877,"Wallach, Jon",60,M,Levittown,NY,USA,NaN,00:24:17,00:48:28,...,7749,165,1457.0,1451.0,1473.0,1499.0,1535.0,1684.0,1801.0,1777.0
11226,14508,"Sclar, Gary",53,M,Harvard,MA,USA,NaN,00:24:22,00:48:37,...,7767,908,1462.0,1455.0,1475.0,1487.0,1541.0,1691.0,1794.0,1788.0
11257,9440,"Cromer, Philip",45,M,Vero Beach,FL,USA,NaN,00:25:00,00:49:52,...,7776,1482,1500.0,1492.0,1484.0,1564.0,1568.0,1638.0,1716.0,1770.0
11310,5835,"Heasley, Mike",41,M,Fort Collins,CO,USA,NaN,00:24:27,00:48:55,...,7805,1336,1467.0,1468.0,1512.0,1549.0,1594.0,1691.0,1772.0,1701.0
11318,15577,"Peters, Thomas W.",64,M,Francestown,NH,USA,NaN,00:23:55,00:48:17,...,7812,171,1435.0,1462.0,1523.0,1518.0,1561.0,1704.0,1767.0,1772.0
11350,12064,"Gardner, Connie J",53,F,Akron,OH,USA,NaN,00:23:12,00:47:53,...,3527,131,1392.0,1481.0,1508.0,1550.0,1587.0,1658.0,1797.0,1774.0
11354,11397,"Gornall, Emily J",26,F,Indianapolis,IN,USA,NaN,00:24:52,00:49:51,...,3529,2446,1492.0,1499.0,1499.0,1525.0,1536.0,1646.0,1801.0,1771.0
11361,16462,"Dorsey, Will",55,M,Green Bay,WI,USA,NaN,00:24:20,00:49:14,...,7830,546,1460.0,1494.0,1521.0,1569.0,1589.0,1661.0,1773.0,1698.0
11370,8513,"Anton, Marcos",41,M,Madrid,NaN,ESP,NaN,00:24:25,00:49:10,...,7835,1339,1465.0,1485.0,1498.0,1533.0,1571.0,1699.0,1778.0,1754.0
11408,12801,"Greenfield, Elizabeth L.",39,F,San Jose,CA,USA,NaN,00:24:13,00:48:26,...,3562,2461,1453.0,1453.0,1474.0,1555.0,1591.0,1680.0,1749.0,1786.0
11420,16505,"Walters, Randi J",29,F,Boise,ID,USA,NaN,00:24:53,00:49:47,...,3569,2464,1493.0,1494.0,1494.0,1516.0,1516.0,1700.0,1803.0,1776.0
11432,10376,"Zomer, Konrad",47,M,Bussum,NaN,NED,NaN,00:24:29,00:48:58,...,7858,1500,1469.0,1469.0,1519.0,1571.0,1582.0,1652.0,1758.0,1778.0
11446,11683,"Fairfax, Walter R",63,M,Coeur D Alene,ID,USA,NaN,00:24:26,00:48:47,...,7864,178,1466.0,1461.0,1482.0,1545.0,1596.0,1673.0,1734.0,1761.0
11483,11708,"Damuth, Kevin",48,M,Salem,OR,USA,NaN,00:23:48,00:48:27,...,7879,1509,1428.0,1479.0,1507.0,1561.0,1579.0,1675.0,1782.0,1776.0
11520,15334,"Midkiff, Sandra",33,F,New York,NY,USA,NaN,00:24:40,00:49:33,...,3626,2491,1480.0,1493.0,1521.0,1565.0,1599.0,1667.0,1739.0,1746.0
11605,15395,"Morris, Jennifer G.",47,F,Collaroy,NaN,AUS,NaN,00:24:04,00:48:30,...,3670,375,1444.0,1466.0,1513.0,1573.0,1598.0,1680.0,1780.0,1788.0
11687,14677,"Shao, Xin",42,F,Fremont,CA,USA,NaN,00:24:31,00:48:57,...,3711,610,1471.0,1466.0,1494.0,1572.0,1596.0,1686.0,1782.0,1753.0
11843,13245,"Karvonen, Daniel H",52,M,Crystal,MN,USA,NaN,00:24:31,00:49:14,...,8043,961,1471.0,1483.0,1496.0,1543.0,1587.0,1693.0,1793.0,1780.0
12083,13708,"Buzza, Shane",51,M,Carmel Valley,CA,USA,NaN,00:24:59,00:49:52,...,8155,984,1499.0,1493.0,1511.0,1547.0,1458.0,1544.0,1671.0,1778.0
12120,8433,"Zhang, Sijian",50,M,Hoboken,NJ,USA,NaN,00:24:22,00:48:55,...,8177,991,1462.0,1473.0,1518.0,1575.0,1613.0,1664.0,1774.0,1776.0
13244,9127,"Moore, Sean",53,M,Yonkers,NY,USA,NaN,00:21:45,00:43:32,...,8694,1085,1305.0,1307.0,1342.0,1373.0,1392.0,1436.0,1475.0,1607.0
18945,797,"Lang, Philip",29,M,New York,NY,USA,NaN,00:19:33,00:39:29,...,11119,3939,1173.0,1196.0,1208.0,1245.0,1260.0,1290.0,1317.0,1331.0
22175,1640,"Hebert, Jordan",25,M,Elmhurst,IL,USA,NaN,00:19:47,00:39:21,...,12551,4246,1187.0,1174.0,1162.0,1167.0,1182.0,1233.0,1318.0,1324.0
24510,8221,"Perry, Emelia",24,F,Cherry Hill,NJ,USA,NaN,00:21:56,00:44:04,...,10919,5347,1316.0,1328.0,1334.0,1332.0,1350.0,1380.0,1409.0,1757.0
24687,10761,"Schacht, Ashley",29,F,Fishers,IN,USA,NaN,00:24:28,00:48:32,...,11015,5389,1468.0,1444.0,1450.0,1457.0,1470.0,1515.0,1557.0,1577.0

In [20]:
auxTable2 = df.groupby('Country').count().sort_values(by='Bib', ascending=False)
auxTable = auxTable2['Bib']
auxTable = auxTable.rename(columns = {'Bib':'niceRun'})
df1 = pd.concat([auxTable, auxTable1], axis=1, sort=True)

In [21]:
df1[0] = df1[0].fillna(value=0)
df1

          0    Bib
ALG     0.0      2
AND     0.0      1
ARG    14.0     36
AUS    66.0    191
AUT     8.0     22
BAR     0.0      4
BDI     1.0      1
BEL     7.0     42
BER     2.0      3
BRA    97.0    205
BRN     1.0      1
BUL     0.0      1
CAN   675.0   1870
CAY     4.0      6
CHI    38.0     73
CHN    60.0    242
COL    46.0     61
CRC    41.0     63
CRO     1.0      5
CZE     3.0     11
DEN    25.0     60
DOM     5.0      9
ECU     2.0      8
EGY     1.0      2
ESA     3.0      6
ESP    38.0    132
EST     6.0      9
ETH     5.0      5
FIN     9.0     15
FLK     1.0      1
..      ...    ...
NGR     0.0      1
NOR    18.0     43
NZL     7.0     34
PAN     4.0      4
PAR     0.0      1
PER    20.0     32
PHI     2.0     10
POL    17.0     32
POR    10.0     16
ROU     2.0      2
RSA     6.0     17
RUS    14.0     29
SIN     9.0     20
SLO     5.0      7
SMR     1.0      1
SRB     1.0      1
SUI    26.0     97
SVK     0.0      6
SWE    25.0     61
TCA     0.0      1
THA     1.0      5
TRI     0.0      1
TUR     2.0      5
TWN    24.0     54
UAE     5.0      7
UKR     1.0      4
URU     0.0      5
USA  6343.0  20945
VEN     6.0      6
ZIM     1.0      1

[91 rows x 2 columns]

In [22]:
def niceRunPorcentage(row):
    return int(round((row[0] * 100) / row[1]))

df1['niceRunPorcentage'] = df1.apply (lambda row: niceRunPorcentage(row),axis=1)

In [23]:
df2 = df1.sort_values(by='Bib', ascending=False).sort_values(by='niceRunPorcentage', ascending=False)
df2

        0  Bib  niceRunPorcentage
KEN   8.0    8                100
VEN   6.0    6                100
BDI   1.0    1                100
BRN   1.0    1                100
FLK   1.0    1                100
KSA   1.0    1                100
MLT   1.0    1                100
NCA   1.0    1                100
SMR   1.0    1                100
JAM   1.0    1                100
SRB   1.0    1                100
ROU   2.0    2                100
LUX   2.0    2                100
PAN   4.0    4                100
ETH   5.0    5                100
ZIM   1.0    1                100
LTU   4.0    5                 80
COL  46.0   61                 75
UAE   5.0    7                 71
GUA  17.0   24                 71
SLO   5.0    7                 71
EST   6.0    9                 67
BER   2.0    3                 67
LAT   2.0    3                 67
CAY   4.0    6                 67
CRC  41.0   63                 65
PER  20.0   32                 62
POR  10.0   16                 62
GRE   3.0    5                 60
FIN   9.0   15                 60
..    ...  ...                ...
MAS   3.0   11                 27
GER  61.0  226                 27
SUI  26.0   97                 27
CZE   3.0   11                 27
CHN  60.0  242                 25
UKR   1.0    4                 25
MAR   3.0   12                 25
ECU   2.0    8                 25
NZL   7.0   34                 21
THA   1.0    5                 20
CRO   1.0    5                 20
PHI   2.0   10                 20
ISR   1.0    5                 20
ISL   5.0   27                 19
BEL   7.0   42                 17
KOR   8.0   88                  9
MGL   0.0    1                  0
BUL   0.0    1                  0
AND   0.0    1                  0
BAR   0.0    4                  0
KUW   0.0    1                  0
GRN   0.0    2                  0
ALG   0.0    2                  0
NGR   0.0    1                  0
PAR   0.0    1                  0
INA   0.0    6                  0
SVK   0.0    6                  0
URU   0.0    5                  0
TCA   0.0    1                  0
TRI   0.0    1                  0

[91 rows x 3 columns]

##