In [1]:
import pandas as pd

In [3]:
train = pd.read_csv("dataset/train.csv")
test = pd.read_csv("dataset/test.csv")
train.sample(5)

          id  label                                              tweet
25247  25248      0  stay calm...stay delighted...stay curious...st...
23227  23228      0  today's #socialmedia workshop went well - make...
14207  14208      0  i am thankful for baby giggles. #thankful #pos...
19125  19126      0  i believe happy girls are the prettiest girls....
20695  20696      0  looking forward to afternoon tea tomorrow @use...

In [8]:
train.shape

(31962, 3)

In [4]:
combi = train.append(test, ignore_index=True)

/home/rcrespillo/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:6211: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

In [6]:
combi.head(10)

   id  label                                              tweet
0   1    0.0   @user when a father is dysfunctional and is s...
1   2    0.0  @user @user thanks for #lyft credit i can't us...
2   3    0.0                                bihday your majesty
3   4    0.0  #model   i love u take with u all the time in ...
4   5    0.0             factsguide: society now    #motivation
5   6    0.0  [2/2] huge fan fare and big talking before the...
6   7    0.0   @user camping tomorrow @user @user @user @use...
7   8    0.0  the next school year is the year for exams.ð...
8   9    0.0  we won!!! love the land!!! #allin #cavs #champ...
9  10    0.0   @user @user welcome here !  i'm   it's so #gr...

In [7]:
combi.tail(10)

          id  label                                              tweet
49149  49150    NaN  loving lifeðºð¸âï¸ð  #createyourfutu...
49150  49151    NaN  black professor demonizes, proposes nazi style...
49151  49152    NaN  learn how to think positive.  #positive   #ins...
49152  49153    NaN  we love the pretty, happy and fresh you! #teen...
49153  49154    NaN  2_damn_tuff-ruff_muff__techno_city-(ng005)-web...
49154  49155    NaN  thought factory: left-right polarisation! #tru...
49155  49156    NaN  feeling like a mermaid ð #hairflip #neverre...
49156  49157    NaN  #hillary #campaigned today in #ohio((omg)) &am...
49157  49158    NaN  happy, at work conference: right mindset leads...
49158  49159    NaN  my   song "so glad" free download!  #shoegaze ...

In [9]:
df = combi

Twits should have less than 140ch

In [10]:
df[df['tweet'].str.len() > 140].head()

      id  label                                              tweet
7      8    0.0  the next school year is the year for exams.ð...
335  336    0.0  watching the @user leadership embrace &amp; ki...
433  434    0.0   @user * sweets ð°ð©ð¬ð­ð«â¨!!!!!! ...
474  475    0.0  this is a shockingly   and increasingly #viole...
565  566    0.0  thank youðsoo muchð pretty @user i feel ...

In [11]:
df[df['tweet'].str.len() > 140].shape

(317, 3)

There must be some f*k simbols encoded in here

In [16]:
df.tweet[335]

"watching the @user leadership embrace &amp; kiss donald's ass is #pathetic &amp;  . this is now the @user pay. a pay of racism &amp; hate. #ripgop"

In [17]:
from bs4 import BeautifulSoup
BeautifulSoup(df.tweet[335], 'lxml').get_text()

"watching the @user leadership embrace & kiss donald's ass is #pathetic &  . this is now the @user pay. a pay of racism & hate. #ripgop"

In [18]:
df['tweet'] = df['tweet'].apply(lambda x : BeautifulSoup(x, 'lxml').get_text())

In [19]:
df[df['tweet'].str.len() > 140].shape

(223, 3)

In [21]:
df.tweet[433]

'@user * sweets ð\x9f\x8d°ð\x9f\x8d©ð\x9f\x8d¬ð\x9f\x8d\xadð\x9f\x8d«â\x9c¨!!!!!! * #instagood #ì\x95\x84ì\x9d´ë\x8f\x8c #å\x81¶å\x83\x8f #idola #idol #à¹\x84à¸\xadà¸\x94à¸\xadà¸¥ #followme #selfie   #ã\x81©ã\x82\x8bã\x81\x88ã\x82\x8câ\x80¦ '

In [22]:
import re
df['tweet'] = df['tweet'].apply(lambda x : re.sub(r'@[A-Za-z0-9]+','',x))

In [23]:
df.tweet[433]

' * sweets ð\x9f\x8d°ð\x9f\x8d©ð\x9f\x8d¬ð\x9f\x8d\xadð\x9f\x8d«â\x9c¨!!!!!! * #instagood #ì\x95\x84ì\x9d´ë\x8f\x8c #å\x81¶å\x83\x8f #idola #idol #à¹\x84à¸\xadà¸\x94à¸\xadà¸¥ #followme #selfie   #ã\x81©ã\x82\x8bã\x81\x88ã\x82\x8câ\x80¦ '

In [24]:
df.shape

(49159, 3)

In [25]:
df.tweet.str.contains('https|http', na=False).count()

49159

Cleaning special simbols and numbers like # and @ -> better f-1 without this

In [27]:
df.tweet[0]

' when a father is dysfunctional and is so selfish he drags his kids into his dysfunction.   #run'

In [15]:
#df['tweet'] = df['tweet'].apply(lambda x : re.sub("[^a-zA-Z]", " ", x))

In [28]:
import nltk
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer

[nltk_data] Downloading package wordnet to
[nltk_data]     /home/rcrespillo/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [29]:
def tweets_lemm(tweet):
    lemmatizer = WordNetLemmatizer()
    word_list = nltk.word_tokenize(tweet)
    lemmatized_output = ' '.join([lemmatizer.lemmatize(w) for w in word_list])
    return lemmatized_output

In [30]:
df['tweet'] = df['tweet'].apply(lambda x : tweets_lemm(x))

In [31]:
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords

In [32]:
nltk.download('punkt')
nltk.download('stopwords')
stops = set(stopwords.words('english'))

[nltk_data] Downloading package punkt to /home/rcrespillo/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /home/rcrespillo/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [33]:
vectorizer = TfidfVectorizer(analyzer='word', 
                             tokenizer=nltk.word_tokenize, 
                             stop_words=stops, 
                             ngram_range=(1,3))

X_train_v = vectorizer.fit(df['tweet'])

In [34]:
vectorizer.vocabulary_

{'father': 279465,
 'dysfunctional': 258865,
 'selfish': 512674,
 'drag': 255697,
 'kid': 366210,
 'dysfunction': 258862,
 '.': 109892,
 '#': 10299,
 'run': 500776,
 'father dysfunctional': 279784,
 'dysfunctional selfish': 258868,
 'selfish drag': 512685,
 'drag kid': 255708,
 'kid dysfunction': 366434,
 'dysfunction .': 258863,
 '. #': 109903,
 '# run': 62525,
 'father dysfunctional selfish': 279785,
 'dysfunctional selfish drag': 258869,
 'selfish drag kid': 512686,
 'drag kid dysfunction': 255709,
 'kid dysfunction .': 366435,
 'dysfunction . #': 258864,
 '. # run': 111942,
 'thanks': 557927,
 'lyft': 397457,
 'credit': 232513,
 'ca': 204761,
 "n't": 424547,
 'use': 587070,
 'cause': 210355,
 'offer': 444079,
 'wheelchair': 607695,
 'van': 588645,
 'pdx': 458202,
 'disapointed': 250332,
 'getthanked': 307230,
 'thanks #': 557936,
 '# lyft': 47841,
 'lyft credit': 397466,
 'credit ca': 232528,
 "ca n't": 204784,
 "n't use": 427275,
 'use cause': 587105,
 "cause n't": 210469,
 "n't offer": 426491,
 'offer wheelchair': 444146,
 'wheelchair van': 607702,
 'van pdx': 588657,
 'pdx .': 458209,
 '# disapointed': 26889,
 'disapointed #': 250333,
 '# getthanked': 34815,
 'thanks # lyft': 557989,
 '# lyft credit': 47843,
 'lyft credit ca': 397467,
 "credit ca n't": 232529,
 "ca n't use": 204966,
 "n't use cause": 427277,
 "use cause n't": 587106,
 "cause n't offer": 210473,
 "n't offer wheelchair": 426492,
 'offer wheelchair van': 444147,
 'wheelchair van pdx': 607703,
 'van pdx .': 588658,
 'pdx . #': 458210,
 '. # disapointed': 110499,
 '# disapointed #': 26890,
 'disapointed # getthanked': 250334,
 'bihday': 188342,
 'majesty': 399291,
 'bihday majesty': 189194,
 'model': 414628,
 'love': 391818,
 'u': 580934,
 'take': 550770,
 'time': 564716,
 'urð\x9f\x93±': 586746,
 '!': 0,
 'ð\x9f\x98\x99ð\x9f\x98\x8eð\x9f\x91\x84ð\x9f\x91': 642929,
 'ð\x9f\x92¦ð\x9f\x92¦ð\x9f\x92¦': 638354,
 '# model': 50326,
 'model love': 414708,
 'love u': 394159,
 'u take': 582406,
 'take u': 551304,
 'u time': 582441,
 'time urð\x9f\x93±': 566103,
 'urð\x9f\x93± !': 586747,
 '! !': 1,
 '! ð\x9f\x98\x99ð\x9f\x98\x8eð\x9f\x91\x84ð\x9f\x91': 9944,
 'ð\x9f\x98\x99ð\x9f\x98\x8eð\x9f\x91\x84ð\x9f\x91 ð\x9f\x92¦ð\x9f\x92¦ð\x9f\x92¦': 642930,
 '# model love': 50329,
 'model love u': 414709,
 'love u take': 394181,
 'u take u': 582412,
 'take u time': 551308,
 'u time urð\x9f\x93±': 582444,
 'time urð\x9f\x93± !': 566104,
 'urð\x9f\x93± ! !': 586748,
 '! ! !': 2,
 '! ! ð\x9f\x98\x99ð\x9f\x98\x8eð\x9f\x91\x84ð\x9f\x91': 734,
 '! ð\x9f\x98\x99ð\x9f\x98\x8eð\x9f\x91\x84ð\x9f\x91 ð\x9f\x92¦ð\x9f\x92¦ð\x9f\x92¦': 9945,
 'factsguide': 275899,
 ':': 139382,
 'society': 527928,
 'motivation': 419046,
 'factsguide :': 275900,
 ': society': 141765,
 'society #': 527932,
 '# motivation': 50909,
 'factsguide : society': 275911,
 ': society #': 141766,
 'society # motivation': 527935,
 '[': 147122,
 '2/2': 131502,
 ']': 147336,
 'huge': 346079,
 'fan': 277837,
 'fare': 278644,
 'big': 187422,
 'talking': 552112,
 'leave': 375886,
 'chaos': 212985,
 'pay': 457371,
 'dispute': 251473,
 'get': 305414,
 'allshowandnogo': 158926,
 '[ 2/2': 147217,
 '2/2 ]': 131505,
 '] huge': 147383,
 'huge fan': 346121,
 'fan fare': 277993,
 'fare big': 278651,
 'big talking': 187774,
 'talking leave': 552204,
 'leave .': 375904,
 '. chaos': 114472,
 'chaos pay': 212992,
 'pay dispute': 457613,
 'dispute get': 251474,
 'get .': 305558,
 '# allshowandnogo': 13525,
 '[ 2/2 ]': 147218,
 '2/2 ] huge': 131506,
 '] huge fan': 147384,
 'huge fan fare': 346125,
 'fan fare big': 277994,
 'fare big talking': 278652,
 'big talking leave': 187775,
 'talking leave .': 552205,
 'leave . chaos': 375906,
 '. chaos pay': 114473,
 'chaos pay dispute': 212993,
 'pay dispute get': 457614,
 'dispute get .': 251475,
 'get . #': 305559,
 '. # allshowandnogo': 109986,
 'camping': 206869,
 'tomorrow': 569619,
 'dannyâ\x80¦': 238324,
 'camping tomorrow': 206889,
 'tomorrow dannyâ\x80¦': 569913,
 'camping tomorrow dannyâ\x80¦': 206891,
 'next': 436285,
 'school': 507216,
 'year': 620927,
 'exams.ð\x9f\x98¯': 272158,
 'think': 560952,
 'ð\x9f\x98\xad': 643719,
 'exam': 272041,
 'hate': 333079,
 'imagine': 350176,
 'actorslife': 153249,
 'revolutionschool': 495697,
 'girl': 308736,
 'next school': 436577,
 'school year': 507547,
 'year year': 621725,
 'year exams.ð\x9f\x98¯': 621360,
 'exams.ð\x9f\x98¯ ca': 272159,
 "n't think": 427136,
 'think ð\x9f\x98\xad': 561686,
 'ð\x9f\x98\xad #': 643722,
 '# school': 63421,
 'school #': 507226,
 '# exam': 30136,
 'exam #': 272047,
 '# hate': 37785,
 'hate #': 333084,
 '# imagine': 40561,
 'imagine #': 350177,
 '# actorslife': 12494,
 'actorslife #': 153250,
 '# revolutionschool': 61594,
 'revolutionschool #': 495698,
 '# girl': 35069,
 'next school year': 436578,
 'school year year': 507550,
 'year year exams.ð\x9f\x98¯': 621728,
 'year exams.ð\x9f\x98¯ ca': 621361,
 "exams.ð\x9f\x98¯ ca n't": 272160,
 "ca n't think": 204957,
 "n't think ð\x9f\x98\xad": 427172,
 'think ð\x9f\x98\xad #': 561687,
 'ð\x9f\x98\xad # school': 643742,
 '# school #': 63422,
 'school # exam': 507238,
 '# exam #': 30138,
 'exam # hate': 272053,
 '# hate #': 37786,
 'hate # imagine': 333105,
 '# imagine #': 40562,
 'imagine # actorslife': 350178,
 '# actorslife #': 12495,
 'actorslife # revolutionschool': 153260,
 '# revolutionschool #': 61595,
 'revolutionschool # girl': 495699,
 'land': 371986,
 'allin': 158706,
 'cavs': 210625,
 'champion': 212234,
 'cleveland': 218882,
 'clevelandcavaliers': 218936,
 'â\x80¦': 628520,
 '! love': 6424,
 'love land': 393516,
 'land !': 371987,
 '! #': 810,
 '# allin': 13476,
 'allin #': 158707,
 '# cavs': 21473,
 'cavs #': 210629,
 '# champion': 21797,
 'champion #': 212235,
 '# cleveland': 22853,
 'cleveland #': 218887,
 '# clevelandcavaliers': 22860,
 'clevelandcavaliers â\x80¦': 218937,
 '! ! love': 265,
 '! love land': 6443,
 'love land !': 393517,
 'land ! !': 371988,
 '! ! #': 3,
 '! # allin': 916,
 '# allin #': 13477,
 'allin # cavs': 158708,
 '# cavs #': 21474,
 'cavs # champion': 210632,
 '# champion #': 21798,
 'champion # cleveland': 212237,
 '# cleveland #': 22855,
 'cleveland # clevelandcavaliers': 218889,
 '# clevelandcavaliers â\x80¦': 22861,
 'welcome': 605756,
 "'m": 85332,
 "'s": 88306,
 'gr8': 319349,
 'welcome !': 605757,
 "! 'm": 3792,
 "'m 's": 85440,
 "'s #": 88324,
 '# gr8': 36194,
 'gr8 !': 319350,
 "welcome ! 'm": 605760,
 "! 'm 's": 3796,
 "'m 's #": 85441,
 "'s # gr8": 88411,
 '# gr8 !': 36195,
 'â\x86\x9d': 628670,
 'ireland': 356722,
 'consumer': 227017,
 'price': 475736,
 'index': 351820,
 '(': 94115,
 'mom': 415047,
 ')': 95458,
 'climbed': 219210,
 'previous': 475590,
 '0.2': 126217,
 '%': 79823,
 '0.5': 126247,
 'may': 405648,
 'blog': 193508,
 'silver': 521366,
 'gold': 314526,
 'forex': 293566,
 'â\x86\x9d #': 628671,
 '# ireland': 41874,
 'ireland consumer': 356753,
 'consumer price': 227026,
 'price index': 475778,
 'index (': 351821,
 '( mom': 94982,
 'mom )': 415103,
 ') climbed': 96077,
 'climbed previous': 219215,
 'previous 0.2': 475610,
 '0.2 %': 126218,
 '% 0.5': 79893,
 '0.5 %': 126248,
 '% may': 80012,
 'may #': 405649,
 '# blog': 18615,
 'blog #': 193515,
 '# silver': 65059,
 'silver #': 521367,
 '# gold': 35660,
 'gold #': 314530,
 '# forex': 32951,
 'â\x86\x9d # ireland': 628748,
 '# ireland consumer': 41878,
 'ireland consumer price': 356754,
 'consumer price index': 227027,
 'price index (': 475779,
 'index ( mom': 351823,
 '( mom )': 94983,
 'mom ) climbed': 415107,
 ') climbed previous': 96078,
 'climbed previous 0.2': 219217,
 'previous 0.2 %': 475611,
 '0.2 % 0.5': 126221,
 '% 0.5 %': 79894,
 '0.5 % may': 126252,
 '% may #': 80013,
 'may # blog': 405652,
 '# blog #': 18617,
 'blog # silver': 193538,
 '# silver #': 65060,
 'silver # gold': 521369,
 '# gold #': 35662,
 'gold # forex': 314534,
 'orlando': 450890,
 'standwithorlando': 536320,
 'pulseshooting': 479667,
 'orlandoshooting': 451393,
 'biggerproblems': 187997,
 'heabreaking': 334633,
 'value': 588552,
 'selfish .': 512681,
 '# orlando': 55493,
 'orlando #': 450898,
 '# standwithorlando': 67121,
 'standwithorlando #': 536321,
 '# pulseshooting': 59685,
 'pulseshooting #': 479668,
 '# orlandoshooting': 55575,
 'orlandoshooting #': 451394,
 '# biggerproblems': 17750,
 'biggerproblems #': 187998,
 '# selfish': 63950,
 'selfish #': 512675,
 '# heabreaking': 38022,
 'heabreaking #': 334637,
 '# value': 74229,
 'value #': 588555,
 '# love': 46975,
 'love #': 391851,
 'selfish . #': 512682,
 '. # orlando': 111643,
 '# orlando #': 55495,
 'orlando # standwithorlando': 450979,
 '# standwithorlando #': 67122,
 'standwithorlando # pulseshooting': 536322,
 '# pulseshooting #': 59686,
 'pulseshooting # orlandoshooting': 479672,
 '# orlandoshooting #': 55576,
 'orlandoshooting # biggerproblems': 451397,
 '# biggerproblems #': 17751,
 'biggerproblems # selfish': 187999,
 '# selfish #': 63951,
 'selfish # heabreaking': 512676,
 '# heabreaking #': 38023,
 'heabreaking # value': 334651,
 '# value #': 74230,
 'value # love': 588557,
 '# love #': 46977,
 'see': 509641,
 'daddy': 236769,
 'today': 567294,
 '80days': 138616,
 'gettingfed': 307815,
 'get see': 306738,
 'see daddy': 510103,
 'daddy today': 236904,
 'today !': 567295,
 '# 80days': 12058,
 '80days #': 138617,
 '# gettingfed': 34825,
 'get see daddy': 306751,
 'see daddy today': 510104,
 'daddy today !': 236905,
 'today ! !': 567296,
 '! # 80days': 854,
 '# 80days #': 12059,
 '80days # gettingfed': 138618,
 'cnn': 220288,
 'call': 205582,
 'michigan': 410497,
 'middle': 410656,
 "'build": 84205,
 'wall': 597677,
 "'": 83383,
 'chant': 212958,
 '``': 147562,
 'tcot': 553332,
 '# cnn': 23059,
 'cnn call': 220312,
 'call #': 205585,
 '# michigan': 49617,
 'michigan middle': 410506,
 'middle school': 410692,
 "school 'build": 507263,
 "'build wall": 84206,
 "wall '": 597689,
 "' chant": 83623,
 'chant ``': 212961,
 '`` #': 147573,
 '# tcot': 69552,
 '# cnn call': 23062,
 'cnn call #': 220313,
 'call # michigan': 205600,
 '# michigan middle': 49621,
 'michigan middle school': 410507,
 "middle school 'build": 410693,
 "school 'build wall": 507264,
 "'build wall '": 84207,
 "wall ' chant": 597690,
 "' chant ``": 83624,
 'chant `` #': 212962,
 '`` # tcot': 147758,
 'comment': 223791,
 'australia': 172076,
 'opkillingbay': 449777,
 'seashepherd': 508804,
 'helpcovedolphins': 337712,
 'thecove': 559121,
 'comment !': 223792,
 '# australia': 15319,
 'australia #': 172077,
 '# opkillingbay': 55336,
 'opkillingbay #': 449778,
 '# seashepherd': 63678,
 'seashepherd #': 508805,
 '# helpcovedolphins': 38449,
 'helpcovedolphins #': 337713,
 '# thecove': 70497,
 'thecove #': 559122,
 'comment ! #': 223794,
 '! # australia': 989,
 '# australia #': 15320,
 'australia # opkillingbay': 172090,
 '# opkillingbay #': 55337,
 'opkillingbay # seashepherd': 449779,
 '# seashepherd #': 63679,
 'seashepherd # helpcovedolphins': 508807,
 '# helpcovedolphins #': 38450,
 'helpcovedolphins # thecove': 337714,
 '# thecove #': 70498,
 'thecove # helpcovedolphins': 559124,
 'ouch': 451908,
 '...': 121974,
 'junior': 363437,
 'angryð\x9f\x98\x90': 164075,
 'got7': 318971,
 'yugyoem': 624542,
 'omg': 446510,
 'ouch ...': 451917,
 '... junior': 124009,
 'junior angryð\x9f\x98\x90': 363444,
 'angryð\x9f\x98\x90 #': 164076,
 '# got7': 36114,
 'got7 #': 318972,
 '# junior': 43339,
 'junior #': 363438,
 '# yugyoem': 78453,
 'yugyoem #': 624543,
 '# omg': 54983,
 'ouch ... junior': 451918,
 '... junior angryð\x9f\x98\x90': 124010,
 'junior angryð\x9f\x98\x90 #': 363445,
 'angryð\x9f\x98\x90 # got7': 164077,
 '# got7 #': 36115,
 'got7 # junior': 318975,
 '# junior #': 43340,
 'junior # yugyoem': 363441,
 '# yugyoem #': 78454,
 'yugyoem # omg': 624544,
 'thankful': 557428,
 'paner': 455089,
 'positive': 471105,
 'thankful paner': 557759,
 'paner .': 455101,
 '# thankful': 70214,
 'thankful #': 557429,
 '# positive': 58486,
 'thankful paner .': 557760,
 'paner . #': 455102,
 '. # thankful': 112233,
 '# thankful #': 70215,
 'thankful # positive': 557461,
 'retweet': 495138,
 'agree': 156093,
 'retweet agree': 495176,
 'agree !': 156094,
 'retweet agree !': 495177,
 'friday': 296551,
 'ð\x9f\x98\x80': 639091,
 'smile': 525632,
 'around': 168798,
 'via': 589793,
 'ig': 348786,
 'user': 587512,
 'cooky': 228037,
 'make': 399435,
 'people': 459155,
 '# friday': 33351,
 'friday !': 296552,
 '! ð\x9f\x98\x80': 9462,
 'ð\x9f\x98\x80 smile': 639168,
 'smile around': 526121,
 'around via': 169062,
 'via ig': 589977,
 'ig user': 348823,
 'user :': 587517,
 ': #': 139387,
 '# cooky': 23992,
 'cooky make': 228055,
 'make people': 400264,
 '# friday !': 33352,
 'friday ! ð\x9f\x98\x80': 296588,
 '! ð\x9f\x98\x80 smile': 9470,
 'ð\x9f\x98\x80 smile around': 639170,
 'smile around via': 526122,
 'around via ig': 169063,
 'via ig user': 589978,
 'ig user :': 348824,
 'user : #': 587518,
 ': # cooky': 139445,
 '# cooky make': 23995,
 'cooky make people': 228056,
 'know': 368938,
 ',': 97123,
 'essential': 267351,
 'oil': 445195,
 'made': 398059,
 'chemical': 214430,
 'know ,': 369054,
 ', essential': 100615,
 'essential oil': 267359,
 'oil made': 445226,
 'made chemical': 398176,
 'chemical .': 214433,
 'know , essential': 369065,
 ', essential oil': 100616,
 'essential oil made': 267362,
 'oil made chemical': 445227,
 'made chemical .': 398177,
 'euro2016': 268009,
 'blaming': 192338,
 'ha': 325418,
 'conceded': 225429,
 'goal': 312619,
 'wa': 593729,
 'fat': 279353,
 'rooney': 499517,
 'gave': 303739,
 'away': 172944,
 'free': 295519,
 'kick': 366010,
 'knowing': 369843,
 'bale': 177539,
 'hit': 340104,
 '# euro2016': 29873,
 'euro2016 people': 268115,
 'people blaming': 459525,
 'blaming ha': 192350,
 'ha conceded': 325699,
 'conceded goal': 225430,
 'goal wa': 312741,
 'wa fat': 594407,
 'fat rooney': 279401,
 'rooney gave': 499524,
 'gave away': 303762,
 'away free': 173089,
 'free kick': 295722,
 'kick knowing': 366055,
 'knowing bale': 369869,
 'bale hit': 177542,
 'hit .': 340120,
 '# euro2016 people': 29904,
 'euro2016 people blaming': 268116,
 'people blaming ha': 459526,
 'blaming ha conceded': 192351,
 'ha conceded goal': 325700,
 'conceded goal wa': 225431,
 'goal wa fat': 312742,
 'wa fat rooney': 594408,
 'fat rooney gave': 279402,
 'rooney gave away': 499525,
 'gave away free': 303764,
 'away free kick': 173090,
 'free kick knowing': 295723,
 'kick knowing bale': 366056,
 'knowing bale hit': 369870,
 'bale hit .': 177543,
 'sad': 501930,
 'little': 385168,
 'dude..': 257983,
 'badday': 176835,
 'coneofshame': 225770,
 'cat': 209719,
 'pissed': 465256,
 'funny': 301169,
 'laugh': 373764,
 'sad little': 502295,
 'little dude..': 385401,
 'dude.. #': 257984,
 '# badday': 15867,
 'badday #': 176836,
 '# coneofshame': 23719,
 'coneofshame #': 225771,
 '# cat': 21375,
 'cat #': 209726,
 '# pissed': 57671,
 'pissed #': 465257,
 '# funny': 33906,
 'funny #': 301174,
 '# laugh': 44951,
 'sad little dude..': 502297,
 'little dude.. #': 385402,
 'dude.. # badday': 257985,
 '# badday #': 15868,
 'badday # coneofshame': 176837,
 '# coneofshame #': 23720,
 'coneofshame # cat': 225772,
 '# cat #': 21377,
 'cat # pissed': 209777,
 '# pissed #': 57672,
 'pissed # funny': 465260,
 '# funny #': 33908,
 'funny # laugh': 301220,
 'product': 476989,
 'day': 239383,
 'happy': 329767,
 'man': 401766,
 'wine': 610349,
 'tool': 571160,
 'weekend': 604516,
 '?': 143086,
 'open': 449209,
 '&': 80110,
 'drink': 256681,
 'product day': 477036,
 'day :': 240375,
 ': happy': 140878,
 'happy man': 331078,
 'man #': 401777,
 '# wine': 76852,
 'wine tool': 610446,
 "tool 's": 571168,
 "'s 's": 88590,
 '# weekend': 75821,
 'weekend ?': 604844,
 '? time': 145383,
 'time open': 565757,
 'open &': 449227,
 '& drink': 81245,
 'drink !': 256682,
 'product day :': 477037,
 'day : happy': 240383,
 ': happy man': 140887,
 'happy man #': 331080,
 'man # wine': 401816,
 '# wine tool': 76860,
 "wine tool 's": 610447,
 "tool 's 's": 571169,
 "'s 's #": 88591,
 "'s # weekend": 88534,
 '# weekend ?': 75829,
 'weekend ? time': 604852,
 '? time open': 145385,
 'time open &': 565758,
 'open & drink': 449228,
 '& drink !': 81246,
 'lumpy': 396976,
 'say': 505726,
 'prove': 478737,
 'lumpy say': 396980,
 'say .': 505857,
 '. prove': 118590,
 'prove lumpy': 478746,
 'lumpy .': 396977,
 'lumpy say .': 396981,
 'say . prove': 505868,
 '. prove lumpy': 118591,
 'prove lumpy .': 478747,
 'tgif': 556610,
 'ff': 284173,
 'gamedev': 302919,
 'indiedev': 352110,
 'indiegamedev': 352130,
 'squad': 534571,
 '# tgif': 70138,
 'tgif #': 556616,
 '# ff': 31720,
 'ff #': 284174,
 '# gamedev': 34204,
 'gamedev #': 302921,
 '# indiedev': 40907,
 'indiedev #': 352111,
 '# indiegamedev': 40915,
 'indiegamedev #': 352131,
 '# squad': 66977,
 'squad !': 534572,
 '# tgif #': 70140,
 'tgif # ff': 556626,
 '# ff #': 31721,
 'ff # gamedev': 284176,
 '# gamedev #': 34206,
 'gamedev # indiedev': 302925,
 '# indiedev #': 40908,
 'indiedev # indiegamedev': 352115,
 '# indiegamedev #': 40916,
 'indiegamedev # squad': 352133,
 '# squad !': 66978,
 'beautiful': 181113,
 'sign': 520903,
 'vendor': 589305,
 '80': 138553,
 '$': 79470,
 '45.00': 136033,
 'upsideofflorida': 586246,
 'shopalyssas': 518651,
 'beautiful sign': 181640,
 'sign vendor': 521020,
 'vendor 80': 589327,
 '80 $': 138559,
 '$ 45.00': 79675,
 '45.00 !': 136034,
 '# upsideofflorida': 73935,
 'upsideofflorida #': 586247,
 '# shopalyssas': 64742,
 'shopalyssas #': 518652,
 'beautiful sign vendor': 181641,
 'sign vendor 80': 521022,
 'vendor 80 $': 589328,
 '80 $ 45.00': 138560,
 '$ 45.00 !': 79676,
 '45.00 ! !': 136035,
 '! # upsideofflorida': 3536,
 '# upsideofflorida #': 73936,
 'upsideofflorida # shopalyssas': 586250,
 '# shopalyssas #': 64743,
 'shopalyssas # love': 518656,
 'medium': 407373,
 'ð\x9f\x98\x9cð\x9f\x98\x88': 643041,
 'pressconference': 475044,
 'antalya': 165737,
 'turkey': 578561,
 'sunday': 545443,
 'throwback': 563295,
 'ð\x9f\x98\x8að\x9f\x98\x98â\x9d¤ï¸\x8f': 641351,
 '# smile': 65705,
 'smile #': 525643,
 '# medium': 49166,
 'medium !': 407374,
 '! ð\x9f\x98\x9cð\x9f\x98\x88': 9955,
 'ð\x9f\x98\x9cð\x9f\x98\x88 #': 643042,
 '# pressconference': 59023,
 'pressconference #': 475045,
 '# antalya': 14428,
 'antalya #': 165738,
 '# turkey': 72995,
 'turkey !': 578562,
 '! sunday': 7770,
 'sunday #': 545462,
 '# throwback': 71240,
 'throwback love': 563333,
 'love !': 391819,
 '! ð\x9f\x98\x8að\x9f\x98\x98â\x9d¤ï¸\x8f': 9756,
 '# smile #': 65707,
 'smile # medium': 525877,
 '# medium !': 49167,
 'medium ! !': 407375,
 '! ! ð\x9f\x98\x9cð\x9f\x98\x88': 739,
 '! ð\x9f\x98\x9cð\x9f\x98\x88 #': 9956,
 'ð\x9f\x98\x9cð\x9f\x98\x88 # pressconference': 643043,
 '# pressconference #': 59024,
 'pressconference # antalya': 475046,
 '# antalya #': 14429,
 'antalya # turkey': 165740,
 '# turkey !': 72996,
 'turkey ! sunday': 578563,
 '! sunday #': 7771,
 'sunday # throwback': 545594,
 '# throwback love': 71246,
 'throwback love !': 563334,
 'love ! ð\x9f\x98\x8að\x9f\x98\x98â\x9d¤ï¸\x8f': 391845,
 'great': 320622,
 'panel': 455067,
 'mediatization': 407259,
 'public': 479241,
 'service': 514127,
 'ica16': 347868,
 'great panel': 321160,
 'panel mediatization': 455080,
 'mediatization public': 407260,
 'public service': 479310,
 'service #': 514132,
 '# ica16': 39990,
 'great panel mediatization': 321161,
 'panel mediatization public': 455081,
 'mediatization public service': 407261,
 'public service #': 479311,
 'service # ica16': 514139,
 'ð\x9f\x92\x93ð\x9f\x92\x93ð\x9f\x92\x93ð\x9f\x92\x93': 637301,
 'happy father': 330717,
 "father 's": 279522,
 "'s day": 89702,
 'day ð\x9f\x92\x93ð\x9f\x92\x93ð\x9f\x92\x93ð\x9f\x92\x93': 242570,
 "happy father 's": 330719,
 "father 's day": 279531,
 "'s day ð\x9f\x92\x93ð\x9f\x92\x93ð\x9f\x92\x93ð\x9f\x92\x93": 89848,
 '50': 136724,
 'went': 606659,
 'nightclub': 438583,
 'good': 315222,
 'night': 437899,
 '1': 126562,
 'action': 152953,
 'mean': 406685,
 'lost': 390919,
 'family': 276902,
 'forever': 293348,
 'rip': 497276,

In [35]:
combi[:31962].tail()

          id  label                                              tweet
31957  31958    0.0  ate isz that youuu ? ððððððð...
31958  31959    0.0  to see nina turner on the airwave trying to wr...
31959  31960    0.0  listening to sad song on a monday morning otw ...
31960  31961    1.0  # sikh # temple vandalised in in # calgary , #...
31961  31962    0.0                           thank you for you follow

In [36]:
train.tail()

          id  label                                              tweet
31957  31958      0  ate @user isz that youuu?ðððððð...
31958  31959      0    to see nina turner on the airwaves trying to...
31959  31960      0  listening to sad songs on a monday morning otw...
31960  31961      1  @user #sikh #temple vandalised in in #calgary,...
31961  31962      0                   thank you @user for you follow

In [38]:
df = combi[:31962]
df['label'] = df['label'].apply(int)
df_test = combi[31962:]

/home/rcrespillo/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [39]:
df.tail()

          id  label                                              tweet
31957  31958      0  ate isz that youuu ? ððððððð...
31958  31959      0  to see nina turner on the airwave trying to wr...
31959  31960      0  listening to sad song on a monday morning otw ...
31960  31961      1  # sikh # temple vandalised in in # calgary , #...
31961  31962      0                           thank you for you follow

In [40]:
X = df["tweet"]
y = df["label"]

In [41]:
from sklearn.model_selection import train_test_split

In [42]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, stratify=y)

In [43]:
X_train_v = vectorizer.transform(X_train)
X_test_v = vectorizer.transform(X_test)

In [44]:
X_train_v.shape

(25569, 645964)

In [45]:
from sklearn.neural_network import MLPClassifier

In [46]:
mlp_clf = MLPClassifier(hidden_layer_sizes=(10,), verbose=True)

In [47]:
mlp_clf.fit(X_train_v, y_train)

Iteration 1, loss = 0.68685951
Iteration 2, loss = 0.41884346
Iteration 3, loss = 0.23259868
Iteration 4, loss = 0.13948359
Iteration 5, loss = 0.08683146
Iteration 6, loss = 0.05649509
Iteration 7, loss = 0.03895366
Iteration 8, loss = 0.02846464
Iteration 9, loss = 0.02182293
Iteration 10, loss = 0.01743129
Iteration 11, loss = 0.01440387
Iteration 12, loss = 0.01225490
Iteration 13, loss = 0.01065687
Iteration 14, loss = 0.00944716
Iteration 15, loss = 0.00850328
Iteration 16, loss = 0.00775422
Iteration 17, loss = 0.00714698
Iteration 18, loss = 0.00664804
Iteration 19, loss = 0.00622627
Iteration 20, loss = 0.00586877
Iteration 21, loss = 0.00556081
Iteration 22, loss = 0.00529160
Iteration 23, loss = 0.00505504
Iteration 24, loss = 0.00484060
Iteration 25, loss = 0.00464634
Iteration 26, loss = 0.00446948
Iteration 27, loss = 0.00430510
Iteration 28, loss = 0.00415299
Iteration 29, loss = 0.00400984
Iteration 30, loss = 0.00387429
Iteration 31, loss = 0.00374532
Iteration 32, loss = 0.00362261
Iteration 33, loss = 0.00350669
Iteration 34, loss = 0.00339339
Iteration 35, loss = 0.00328461
Iteration 36, loss = 0.00318040
Iteration 37, loss = 0.00308265
Iteration 38, loss = 0.00298400
Iteration 39, loss = 0.00289218
Training loss did not improve more than tol=0.000100 for two consecutive epochs. Stopping.

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(10,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=True, warm_start=False)

In [48]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_auc_score, classification_report

In [49]:
y_pred = mlp_clf.predict(X_test_v)

In [50]:
#confusion_matrix(y_test, y_pred)

In [51]:
print("roc_auc score: {}".format(roc_auc_score(y_test, y_pred)))
print(classification_report(y_test, y_pred))

roc_auc score: 0.7273421542712964
             precision    recall  f1-score   support

          0       0.96      1.00      0.98      5945
          1       0.98      0.46      0.62       448

avg / total       0.96      0.96      0.95      6393

In [52]:
X_all = vectorizer.transform(X)
y_all = y

In [53]:
mlp_clf.fit(X_all, y_all)

Iteration 1, loss = 0.37187057
Iteration 2, loss = 0.19711834
Iteration 3, loss = 0.11764722
Iteration 4, loss = 0.06719091
Iteration 5, loss = 0.03977318
Iteration 6, loss = 0.02577845
Iteration 7, loss = 0.01822890
Iteration 8, loss = 0.01384055
Iteration 9, loss = 0.01111182
Iteration 10, loss = 0.00930332
Iteration 11, loss = 0.00803352
Iteration 12, loss = 0.00711171
Iteration 13, loss = 0.00641456
Iteration 14, loss = 0.00586933
Iteration 15, loss = 0.00542660
Iteration 16, loss = 0.00505980
Iteration 17, loss = 0.00474739
Iteration 18, loss = 0.00447635
Iteration 19, loss = 0.00423642
Iteration 20, loss = 0.00401920
Iteration 21, loss = 0.00382265
Iteration 22, loss = 0.00364264
Iteration 23, loss = 0.00347678
Iteration 24, loss = 0.00332119
Iteration 25, loss = 0.00317655
Iteration 26, loss = 0.00304041
Iteration 27, loss = 0.00291314
Iteration 28, loss = 0.00279395
Iteration 29, loss = 0.00267699
Iteration 30, loss = 0.00257331
Iteration 31, loss = 0.00247243
Iteration 32, loss = 0.00237871
Iteration 33, loss = 0.00228560
Iteration 34, loss = 0.00219953
Training loss did not improve more than tol=0.000100 for two consecutive epochs. Stopping.

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(10,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=True, warm_start=False)

In [54]:
df_test.sample(5)

          id  label                                              tweet
37181  37182    NaN  # goodmorning # world it ` s a # rainingday an...
39938  39939    NaN  happy thursday ! do n't let the rain dampen yo...
48043  48044    NaN  soo excited to see you in chitty tonight ! eek...
47982  47983    NaN  the fn is seeking to rid of it anti-semitic , ...
43184  43185    NaN  my girl ð # familyman # mygirls # lovethem ...

In [55]:
dtest = vectorizer.transform(df_test['tweet'])
test_pred = mlp_clf.predict(dtest)

In [56]:
df_test['label'] = test_pred

/home/rcrespillo/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [57]:
submission = df_test[['id','label']]

In [58]:
submission.to_csv('sub_rodixxi_mlpc_cleanData_lemma_3.csv', index=False)